### ISSUE TITLE
Update GNOME 44 runtime for dino flatpak

### ISSUE THREAD

**Issue by heredia21** [mxlgv/dino#84]
Receiving the following message when updating my flatpaks:

Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   im.dino.Dino

Can this get updated to use a newer version?

**Comment by mxlgv** [comment]
@heredia21 fixed https://github.com/mxlgv/dino/commit/edd0249b20c55753258e10a2aa7a4bd47d217603
